#pragma once

#include <torch/csrc/distributed/ddp/event.h>

#include <vector>


namespace torch {
namespace distributed {
namespace ddp {

using c10::ivalue::Future;

class EventHandler {
 public:
  virtual std::vector<EventSchema> ingressEvents() = 0;
  virtual std::vector<EventSchema> egressEvents() = 0;
  // returned Future contents Event objects generated by this handler.
  virtual std::vector<std::shared_ptr<Future>> handleEvent(const Event&) = 0;
};

class RootHandler : public EventHandler {
 public:
  std::vector<EventSchema> ingressEvents() override {
    return {};
  }

  std::vector<EventSchema> egressEvents() override {
    return {
        EventType::PREPARE_MODULE,
        EventType::PRE_FORWARD,
        EventType::POST_FORWARD};
  }

  std::vector<std::shared_ptr<Future>> handleEvent(const Event&) override {
    TORCH_INTERNAL_ASSERT(false);
  }
};


class DefaultTrigger : public EventHandler {
 public:
  std::vector<EventSchema> ingressEvents() override {
    return {EventType::PREPARE_MODULE};
  }

  std::vector<EventSchema> egressEvents() override {
    return {EventType::GRAD_READY};
  }

  std::vector<std::shared_ptr<Future>> handleEvent(const Event&) override {
    TORCH_INTERNAL_ASSERT(false);
  }
};

} // namespace ddp
} // namespace distributed
} // namespace torch
